# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pi/canInspector/ui/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1278, 861)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.camera = QtWidgets.QLabel(self.centralwidget)
        self.camera.setGeometry(QtCore.QRect(10, 10, 411, 821))
        self.camera.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.camera.setAutoFillBackground(False)
        self.camera.setFrameShape(QtWidgets.QFrame.Box)
        self.camera.setFrameShadow(QtWidgets.QFrame.Plain)
        self.camera.setText("")
        self.camera.setPixmap(QtGui.QPixmap("../../Desktop/1.jpg"))
        self.camera.setScaledContents(True)
        self.camera.setObjectName("camera")
        self.textBox_canInspected = QtWidgets.QLabel(self.centralwidget)
        self.textBox_canInspected.setGeometry(QtCore.QRect(780, 0, 421, 131))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.textBox_canInspected.setFont(font)
        self.textBox_canInspected.setAlignment(QtCore.Qt.AlignCenter)
        self.textBox_canInspected.setObjectName("textBox_canInspected")
        self.textBox_canInspected_2 = QtWidgets.QLabel(self.centralwidget)
        self.textBox_canInspected_2.setGeometry(QtCore.QRect(460, 0, 311, 131))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.textBox_canInspected_2.setFont(font)
        self.textBox_canInspected_2.setAlignment(QtCore.Qt.AlignCenter)
        self.textBox_canInspected_2.setObjectName("textBox_canInspected_2")
        self.textBox_canRejected = QtWidgets.QLabel(self.centralwidget)
        self.textBox_canRejected.setGeometry(QtCore.QRect(780, 110, 421, 101))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.textBox_canRejected.setFont(font)
        self.textBox_canRejected.setAlignment(QtCore.Qt.AlignCenter)
        self.textBox_canRejected.setObjectName("textBox_canRejected")
        self.textBox_canInspected_4 = QtWidgets.QLabel(self.centralwidget)
        self.textBox_canInspected_4.setGeometry(QtCore.QRect(450, 110, 311, 91))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.textBox_canInspected_4.setFont(font)
        self.textBox_canInspected_4.setAlignment(QtCore.Qt.AlignCenter)
        self.textBox_canInspected_4.setObjectName("textBox_canInspected_4")
        self.textBox_linePerfomance = QtWidgets.QLabel(self.centralwidget)
        self.textBox_linePerfomance.setGeometry(QtCore.QRect(680, 240, 141, 71))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textBox_linePerfomance.setFont(font)
        self.textBox_linePerfomance.setAlignment(QtCore.Qt.AlignCenter)
        self.textBox_linePerfomance.setObjectName("textBox_linePerfomance")
        self.textBox_canInspected_6 = QtWidgets.QLabel(self.centralwidget)
        self.textBox_canInspected_6.setGeometry(QtCore.QRect(450, 240, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textBox_canInspected_6.setFont(font)
        self.textBox_canInspected_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.textBox_canInspected_6.setObjectName("textBox_canInspected_6")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(450, 210, 721, 20))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(810, 220, 20, 611))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.textBox_machinePerfomance = QtWidgets.QLabel(self.centralwidget)
        self.textBox_machinePerfomance.setGeometry(QtCore.QRect(680, 300, 141, 71))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textBox_machinePerfomance.setFont(font)
        self.textBox_machinePerfomance.setAlignment(QtCore.Qt.AlignCenter)
        self.textBox_machinePerfomance.setObjectName("textBox_machinePerfomance")
        self.textBox_canInspected_8 = QtWidgets.QLabel(self.centralwidget)
        self.textBox_canInspected_8.setGeometry(QtCore.QRect(450, 300, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textBox_canInspected_8.setFont(font)
        self.textBox_canInspected_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.textBox_canInspected_8.setObjectName("textBox_canInspected_8")
        self.textBox_mode = QtWidgets.QLabel(self.centralwidget)
        self.textBox_mode.setGeometry(QtCore.QRect(680, 360, 141, 71))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textBox_mode.setFont(font)
        self.textBox_mode.setAlignment(QtCore.Qt.AlignCenter)
        self.textBox_mode.setObjectName("textBox_mode")
        self.textBox_canInspected_10 = QtWidgets.QLabel(self.centralwidget)
        self.textBox_canInspected_10.setGeometry(QtCore.QRect(450, 360, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textBox_canInspected_10.setFont(font)
        self.textBox_canInspected_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.textBox_canInspected_10.setObjectName("textBox_canInspected_10")
        self.emergencyStop = QtWidgets.QLabel(self.centralwidget)
        self.emergencyStop.setGeometry(QtCore.QRect(890, 390, 231, 221))
        self.emergencyStop.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.emergencyStop.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.emergencyStop.setAutoFillBackground(False)
        self.emergencyStop.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.emergencyStop.setFrameShadow(QtWidgets.QFrame.Plain)
        self.emergencyStop.setText("")
        self.emergencyStop.setPixmap(QtGui.QPixmap("/home/pi/canInspector/ui/emergencyStop.png"))
        self.emergencyStop.setScaledContents(True)
        self.emergencyStop.setObjectName("emergencyStop")
        self.textBox_canInspected_11 = QtWidgets.QLabel(self.centralwidget)
        self.textBox_canInspected_11.setGeometry(QtCore.QRect(860, 260, 300, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBox_canInspected_11.sizePolicy().hasHeightForWidth())
        self.textBox_canInspected_11.setSizePolicy(sizePolicy)
        self.textBox_canInspected_11.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.textBox_canInspected_11.setFont(font)
        self.textBox_canInspected_11.setTextFormat(QtCore.Qt.RichText)
        self.textBox_canInspected_11.setScaledContents(False)
        self.textBox_canInspected_11.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.textBox_canInspected_11.setObjectName("textBox_canInspected_11")
        self.textBox_canInspected_12 = QtWidgets.QLabel(self.centralwidget)
        self.textBox_canInspected_12.setGeometry(QtCore.QRect(850, 330, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.textBox_canInspected_12.setFont(font)
        self.textBox_canInspected_12.setAlignment(QtCore.Qt.AlignCenter)
        self.textBox_canInspected_12.setObjectName("textBox_canInspected_12")
        self.tableJournal = QtWidgets.QTableView(self.centralwidget)
        self.tableJournal.setGeometry(QtCore.QRect(440, 510, 371, 201))
        self.tableJournal.setObjectName("tableJournal")

        # Устанавливаем заголовки таблицы

        self.textBox_status = QtWidgets.QLabel(self.centralwidget)
        self.textBox_status.setGeometry(QtCore.QRect(680, 430, 141, 71))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textBox_status.setFont(font)
        self.textBox_status.setAlignment(QtCore.Qt.AlignCenter)
        self.textBox_status.setObjectName("textBox_status")
        self.textBox_canInspected_14 = QtWidgets.QLabel(self.centralwidget)
        self.textBox_canInspected_14.setGeometry(QtCore.QRect(450, 430, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.textBox_canInspected_14.setFont(font)
        self.textBox_canInspected_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.textBox_canInspected_14.setObjectName("textBox_canInspected_14")
        self.onOffButton = QtWidgets.QPushButton(self.centralwidget)
        self.onOffButton.setGeometry(QtCore.QRect(440, 750, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.onOffButton.setFont(font)
        self.onOffButton.setObjectName("onOffButton")
        self.kvitButton = QtWidgets.QPushButton(self.centralwidget)
        self.kvitButton.setGeometry(QtCore.QRect(960, 690, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.kvitButton.setFont(font)
        self.kvitButton.setStyleSheet("background: rgb(0, 0, 255);\n"
"border-radius: 50%;")
        self.kvitButton.setText("")
        self.kvitButton.setObjectName("kvitButton")
        self.settingsButton = QtWidgets.QPushButton(self.centralwidget)
        self.settingsButton.setGeometry(QtCore.QRect(690, 750, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.settingsButton.setFont(font)
        self.settingsButton.setObjectName("settingsButton")
        self.textBox_canInspected_16 = QtWidgets.QLabel(self.centralwidget)
        self.textBox_canInspected_16.setGeometry(QtCore.QRect(870, 610, 291, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBox_canInspected_16.sizePolicy().hasHeightForWidth())
        self.textBox_canInspected_16.setSizePolicy(sizePolicy)
        self.textBox_canInspected_16.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("Bitstream Vera Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.textBox_canInspected_16.setFont(font)
        self.textBox_canInspected_16.setTextFormat(QtCore.Qt.RichText)
        self.textBox_canInspected_16.setScaledContents(False)
        self.textBox_canInspected_16.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.textBox_canInspected_16.setObjectName("textBox_canInspected_16")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Can Inspector"))
        self.textBox_canInspected.setText(_translate("MainWindow", "00000023000"))
        self.textBox_canInspected_2.setText(_translate("MainWindow", "Examined:"))
        self.textBox_canRejected.setText(_translate("MainWindow", "00000001000"))
        self.textBox_canInspected_4.setText(_translate("MainWindow", "Defected:"))
        self.textBox_linePerfomance.setText(_translate("MainWindow", "100 c/h"))
        self.textBox_canInspected_6.setText(_translate("MainWindow", "Line perfomance:"))
        self.textBox_machinePerfomance.setText(_translate("MainWindow", "300 c/h"))
        self.textBox_canInspected_8.setText(_translate("MainWindow", "Machine perfomance:"))
        self.textBox_mode.setText(_translate("MainWindow", "AI"))
        self.textBox_canInspected_10.setText(_translate("MainWindow", "Mode:"))
        self.textBox_canInspected_11.setText(_translate("MainWindow", "Emergency "))
        self.textBox_canInspected_12.setText(_translate("MainWindow", "Stop"))
        self.textBox_status.setText(_translate("MainWindow", "Ready"))
        self.textBox_canInspected_14.setText(_translate("MainWindow", "Machine Status:"))
        self.onOffButton.setText(_translate("MainWindow", "Machine ON"))
        self.settingsButton.setText(_translate("MainWindow", "Settings"))
        self.textBox_canInspected_16.setText(_translate("MainWindow", "Fault eliminated "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

